# Generated by Django 2.1.1 on 2018-12-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexpapi', '0002_auto_20181118_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tzname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Timezone Name'),
        ),
    ]
